version: '3'
services:
  appiumtest:
    build: .
    image: appiumtest:latest
    ports:
      - "5555:5555"
      - "5554:5554"
      - "6080:6080"
      - "4723:4723"
    command: bash -c "./install_apk.sh --user root && appium"
